pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Readwide"
include ':app'
include ':libarchiveAndroid'
project(':libarchiveAndroid').projectDir = file('third_party/libarchive-android/library')
include ':zipxCodecsAndroid'
project(':zipxCodecsAndroid').projectDir = file('third_party/zipx-codecs-android/library')
