package com.readwide.manager.document.doc;

import com.readwide.manager.document.render.ParagraphStyle;
import com.readwide.manager.document.render.RenderedBlock;
import com.readwide.manager.document.render.RenderedDocument;
import com.readwide.manager.document.render.RenderedPage;
import com.readwide.manager.document.render.RenderedParagraph;
import com.readwide.manager.document.render.RenderedRun;
import com.readwide.manager.document.render.TextStyle;

import org.junit.Test;

import java.util.Base64;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * Validates the legacy binary .doc reader against real Word 97 files produced by
 * LibreOffice. PLAIN_DOC carries English, Korean, and mixed content (stage 1
 * text and paragraph splitting); FORMATTED_DOC carries bold, italic, underline,
 * a larger font size, and a color run (stage 2 character formatting); PARA_DOC
 * carries centered, right-aligned, justified, and indented paragraphs (stage 3
 * paragraph formatting). All fixtures are embedded as base64 so no binary test
 * resource is required.
 */
public class DocLegacyLayoutExtractorTest {

    private static final String PLAIN_DOC = ""
            + "0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAOwADAP7/CQAGAAAAAAAAAAAAAAABAAAAEQAAAAAAAAAAEAAAAgAAAAEAAAD+////AAAA"
            + "AAAAAAD/////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "///////////////////////////////////////////////////////////////////////////////////9//////////7///8E"
            + "AAAABQAAAAYAAAAHAAAA/v///wkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAAQAAAA/v///xIAAAD+////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "/////////////////////////////////////////////////////////////////1IAbwBvAHQAIABFAG4AdAByAHkAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//"
            + "/////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAQAAAP7////+////BAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAA"
            + "AAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAAB0A"
            + "AAAeAAAAHwAAACAAAAAhAAAAIgAAAP7///8kAAAAJQAAAP7///8nAAAA/v//////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "//////////////////////////////8BAP7/AwoAAP////8GCQIAAAAAAMAAAAAAAABGGAAAAE1pY3Jvc29mdCBXb3JkLURva3Vt"
            + "ZW50AAoAAABNU1dvcmREb2MAEAAAAFdvcmQuRG9jdW1lbnQuOAD0ObJxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAEAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASABUACgABAFsA"
            + "DwAAAAAAAAAAAFoAABDx/wIAWgAAAAYATgBvAHIAbQBhAGwAAAALAAAAMSQAKiQBQSQAAC8AQioAT0oDAFFKAwBDShgAbUgJBHNI"
            + "CQRQSgQAbkgECHRIBAheSgUAYUoYAF9IOQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEYA/h8BAAIBRgAAAAcASABlAGEA"
            + "ZABpAG4AZwAAAA0ADwATpPAAFKR4AAYkAQAYAE9KBgBRSgYAQ0ocAFBKBwBeSgUAYUocADQAQhABAAIBNAAAAAkAQgBvAGQAeQAg"
            + "AFQAZQB4AHQAAAAQABAAEmQUAQEAE6QAABSkjAAAACAALxABARIBIAAAAAQATABpAHMAdAAAAAIAEQAEAF5KCABAACIQAQAiAUAA"
            + "AAAHAEMAYQBwAHQAaQBvAG4AAAANABIAE6R4ABSkeAAMJAEAEgBDShgANggBXkoIAGFKGABdCAEmAP4fAQAyASYAAAAFAEkAbgBk"
            + "AGUAeAAAAAUAEwAMJAEABABeSggAVgD+HwEAQgFWAAAAEQBQAHIAZQBmAG8AcgBtAGEAdAB0AGUAZAAgAFQAZQB4AHQAAAAKABQA"
            + "E6QAABSkAAAYAE9KCQBRSgkAQ0oUAFBKCgBeSgkAYUoUAAAAAAAoAQAABAAAEAAAAAD/////AAgAAE4KAAAGAAAAAAgAAFAKAAAH"
            + "AAAAAAAAACgBAAAAAAAAAhAAAAAAAAAAKAEAAFAAAAgAAAAACwAAAEcWkAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAABUAGkAbQBlAHMAIABOAGUAdwAgAFIAbwBtAGEAbgAAADUWkAECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AABTAHkAbQBiAG8AbAAAADMmkAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAHIAaQBhAGwAAABpFpABABEA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATABpAGIAZQByAGEAdABpAG8AbgAgAFMAZQByAGkAZgAAAFQAaQBtAGUA"
            + "cwAgAE4AZQB3ACAAUgBvAG0AYQBuAAAASwaQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4AbwB0AG8AIABT"
            + "AGUAcgBpAGYAIABDAEoASwAgAFMAQwAAADkGkAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGAHIAZQBlAFMA"
            + "YQBuAHMAAABTJpABABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATABpAGIAZQByAGEAdABpAG8AbgAgAFMAYQBu"
            + "AHMAAABBAHIAaQBhAGwAAABJBpABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATgBvAHQAbwAgAFMAYQBuAHMA"
            + "IABDAEoASwAgAFMAQwAAADkkkAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGAHIAZQBlAFMAYQBuAHMAAABf"
            + "NZABABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATABpAGIAZQByAGEAdABpAG8AbgAgAE0AbwBuAG8AAABDAG8A"
            + "dQByAGkAZQByACAATgBlAHcAAABTNZABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATgBvAHQAbwAgAFMAYQBu"
            + "AHMAIABNAG8AbgBvACAAQwBKAEsAIABTAEMAAABCAAQAAQiNGAAAxQIAAGgBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAEoAAAAhAQAA"
            + "AQAEAAAABACDkAQAAABKAAAAIQEAAAEABAAAAAQAAAAAAAAAJwMAIAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIwAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA"
            + "AAAAAAAAAAAAAAAAACAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAP7/AAABAAIAAAAAAAAAAAAAAAAAAAAAAAEAAADghZ/y+U9oEKuRCAArJ7PZMAAAAHwAAAAGAAAAAQAAADgA"
            + "AAAJAAAAQAAAAAoAAABMAAAACwAAAFgAAAAMAAAAZAAAAA0AAABwAAAAAgAAAOn9AAAeAAAAAgAAADAAAABAAAAAAAAAAAAAAABA"
            + "AAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7/AAABAAIAAAAAAAAAAAAAAAAA"
            + "AAAAAAIAAAAC1c3VnC4bEJOXCAArLPmuRAAAAAXVzdWcLhsQk5cIACss+a5cAAAAGAAAAAEAAAABAAAAEAAAAAIAAADp/QAAGAAA"
            + "AAEAAAABAAAAEAAAAAIAAADp/QAAAAAAAAAAAAAAAAAA7KUBAU0gCQQAAPASvwAAAAAAADAAAAAAAAgAAFAKAAAOAENhb2xhbjgw"
            + "AAAAAAAAAAAAAAAAAAAAAAAACQQWAC8QAAAAAAAAAAAAACgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8PAAYAAAAB"
            + "AAAA//8PAAcAAAABAAAA//8PAAAAAAAAAAAAAAAAAAAAAACIAAAAAADuAQAAAAAAAO4BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAO4BAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAAAMAAAADgIAAAwAAAAA"
            + "AAAAAAAAADsCAAAyAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAABoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbQUAAGICAAAAAAAAAAAA"
            + "ACYCAAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoCAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAIA2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSAGUAYQBkAHcAaQBkAGUAIABs"
            + "AGUAZwBhAGMAeQAgAC4AZABvAGMAIAB0AGUAcwB0ACAAZABvAGMAdQBtAGUAbgB0AA0ADQBUAGgAaQBzACAAaQBzACAAdABoAGUA"
            + "IABmAGkAcgBzAHQAIABwAGEAcgBhAGcAcgBhAHAAaAAgAGkAbgAgAEUAbgBnAGwAaQBzAGgALgAgAEkAdAAgAGgAYQBzACAAbQB1"
            + "AGwAdABpAHAAbABlACAAcwBlAG4AdABlAG4AYwBlAHMAIAB0AG8AIABlAHgAZQByAGMAaQBzAGUAIAB0AGgAZQAgAHAAaQBlAGMA"
            + "ZQAgAHQAYQBiAGwAZQAgAGEAbgBkACAAcABhAHIAYQBnAHIAYQBwAGgAIABzAHAAbABpAHQAdABpAG4AZwAuAA0ADQBQtCAAiLz4"
            + "ySAAOLvoskDHIABc1QCuhcfIsuSyLgAgACDHyLJUz9y0IABwyAGsKABVAFQARgAtADEANgBMAEUAKQD8rCAAQQBOAFMASQAgAHDI"
            + "AawgAJjMrLl8uSAAVdZ4x1jVMK4gAATHXNUgAIOshcfIsuSyLgANAA0AVABoAGkAcgBkACAAcABhAHIAYQBnAHIAYQBwAGgAOgAg"
            + "AG0AaQB4AGUAZAAgAFzVAK4gAGEAbgBkACAARQBuAGcAbABpAHMAaAAgADEAMgAzADQANQAgACEAQAAjACQAJQAgAHQAbwAgAHQA"
            + "ZQBzAHQAIABjAGgAYQByAGEAYwB0AGUAcgAgAGQAZQBjAG8AZABpAG4AZwAuAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAE4KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAEACAAARggAAEgIAAA2CQAAOAkAALIJAAC0CQAAUAoAAPUAAAAAAAAAAAAAAAD1AAAAAAAAAAAAAAAA"
            + "9QAAAAAAAAAAAAAAAPUAAAAAAAAAAAAAAAD1AAAAAAAAAAAAAAAA9QAAAAAAAAAAAAAAAPUAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAChQAAyQAYSQAE6QAABSkAABB"
            + "JAAABy0APDAAQFAAAEJQAgAfsIIuILDGQSGwbgQisG4EI5BuBCSQbgQzUAAAKDIADjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUgBvAG8AdAAg"
            + "AEUAbgB0AHIAeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYABQD//////////wEAAAAGCQIA"
            + "AAAAAMAAAAAAAABGAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAoAAAAAAAABAEMAbwBtAHAATwBiAGoAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgACAAIAAAAEAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAABqAAAAAAAAAAEATwBsAGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAKAAIA/////wMAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAABQAAAAAAAAA"
            + "MQBUAGEAYgBsAGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAgD/////////"
            + "//////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAzwcAAAAAAAAFAFMAdQBtAG0AYQByAHkASQBuAGYA"
            + "bwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAACAAUAAAAGAAAA/////wAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAACMAAACsAAAAAAAAAFcAbwByAGQARABvAGMAdQBtAGUAbgB0AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAaAAIA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAA"
            + "AC8QAAAAAAAABQBEAG8AYwB1AG0AZQBuAHQAUwB1AG0AbQBhAHIAeQBJAG4AZgBvAHIAbQBhAHQAaQBvAG4AAAAAAAAAAAAAADgA"
            + "AgD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmAAAAdAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7///8AAAAAAAAAAA==";

    private static final String FORMATTED_DOC = ""
            + "0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAOwADAP7/CQAGAAAAAAAAAAAAAAABAAAAEAAAAAAAAAAAEAAAAgAAAAEAAAD+////AAAA"
            + "AAAAAAD/////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "///////////////////////////////////////////////////////////////////////////////////9//////////7///8E"
            + "AAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAD+////EQAAAP7/////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "/////////////////////////////////////////////////////////////////1IAbwBvAHQAIABFAG4AdAByAHkAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//"
            + "/////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAQAAAP7////+////BAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAA"
            + "AAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAAB0A"
            + "AAAeAAAAHwAAACAAAAAhAAAAIgAAACMAAAAkAAAAJQAAACYAAAAnAAAA/v///ykAAAAqAAAA/v///ywAAAAtAAAALgAAAC8AAAAw"
            + "AAAAMQAAADIAAAAzAAAANAAAADUAAAA2AAAANwAAADgAAAA5AAAAOgAAADsAAAA8AAAAPQAAAD4AAAA/AAAAQAAAAEEAAABCAAAA"
            + "QwAAAEQAAABFAAAARgAAAEcAAABIAAAASQAAAEoAAABLAAAATAAAAE0AAABOAAAATwAAAFAAAABRAAAAUgAAAFMAAABUAAAAVQAA"
            + "AFYAAABXAAAAWAAAAFkAAABaAAAAWwAAAFwAAABdAAAAXgAAAF8AAABgAAAAYQAAAGIAAABjAAAA/v///2UAAAD+////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "//////////////////////////////8BAP7/AwoAAP////8GCQIAAAAAAMAAAAAAAABGGAAAAE1pY3Jvc29mdCBXb3JkLURva3Vt"
            + "ZW50AAoAAABNU1dvcmREb2MAEAAAAFdvcmQuRG9jdW1lbnQuOAD0ObJxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAEAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAB0ACgABAFsA"
            + "DwAAAAAAAAAAAFoAABDx/wIAWgAAAAYATgBvAHIAbQBhAGwAAAALAAAAMSQAKiQBQSQAAC8AQioAT0oDAFFKAwBDShgAbUgJBHNI"
            + "CQRQSgQAbkgECHRIBAheSgUAYUoYAF9IOQQAPAABEMEBsgE8AAAACQBIAGUAYQBkAGkAbgBnACAAMQAAAAIAAQAWAE9KBgBRSgYA"
            + "Q0owADUIAWFKLABcCAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQA/h/y//EANAAAABIARQBuAGQAbgBvAHQAZQAgAEMAaABh"
            + "AHIAYQBjAHQAZQByAHMAAAAAADYA/h/y/wEBNgAAABMARgBvAG8AdABuAG8AdABlACAAQwBoAGEAcgBhAGMAdABlAHIAcwAAAAAA"
            + "LgBVEPL/EQEuAAAACQBIAHkAcABlAHIAbABpAG4AawAAAAwAQioJcGgAAIAAPioBggD+HwEAsgGCAAAADwBIAG8AcgBpAHoAbwBu"
            + "AHQAYQBsACAATABpAG4AZQAAAE4AEgATpAAAFKQbASRkAAAAAE7GCAAAAAAAAAAAJWQAAAAAT8YIAAAAAAAAAAAmZAMDDwBQxgiA"
            + "gIAAAwMAACdkAAAAAFHGCAAAAAAAAAAABABDSgwANgAlEAEAMgE2AAAADwBFAG4AdgBlAGwAbwBwAGUAIABSAGUAdAB1AHIAbgAA"
            + "AAIAEwADADYIAQAwAP4fsQFCATAAAAAOAFQAYQBiAGwAZQAgAEMAbwBuAHQAZQBuAHQAcwAAAAIAFAAAAC4AIBABAFIBLgAAAAYA"
            + "RgBvAG8AdABlAHIAAAAQABUADcYIAALSEqUlAQIMJAEAAC4AHxABAGIBLgAAAAYASABlAGEAZABlAHIAAAAQABYADcYIAALSEqUl"
            + "AQIMJAEAAEQA/h8BAHIBRAAAABEASABlAGEAZABlAHIAIABhAG4AZAAgAEYAbwBvAHQAZQByAAAAEAAXAA3GCAAC0xKmJQECDCQB"
            + "AAAmAP4fAQCCASYAAAAFAEkAbgBkAGUAeAAAAAUAGAAMJAEABABeSgcAQAAiEAEAkgFAAAAABwBDAGEAcAB0AGkAbwBuAAAADQAZ"
            + "ABOkeAAUpHgADCQBABIAQ0oYADYIAV5KBwBhShgAXQgBIAAvELEBogEgAAAABABMAGkAcwB0AAAAAgAaAAQAXkoHAC4AQhABALIB"
            + "LgAAAAkAQgBvAGQAeQAgAFQAZQB4AHQAAAAKABsAE6QAABSkGwEAAD4A/h8BALIBPgAAAAcASABlAGEAZABpAG4AZwAAAA0AHAAT"
            + "pPAAFKQbAQYkAQAQAE9KCABRSggAQ0ocAGFKHAAAAAAAYgAAAAQAAA4AAAAA/////wAIAADCCAAABQAAAAAIAADECAAABgAAAAAA"
            + "AABiAAAAAAAAAAIQAAAAAAAAAGIAAABQAAAIAAAAAAkAAABHFpABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "VABpAG0AZQBzACAATgBlAHcAIABSAG8AbQBhAG4AAAA1FpABAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUwB5"
            + "AG0AYgBvAGwAAAAzJpABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQQByAGkAYQBsAAAAaRaQAQARAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEwAaQBiAGUAcgBhAHQAaQBvAG4AIABTAGUAcgBpAGYAAABUAGkAbQBlAHMAIABO"
            + "AGUAdwAgAFIAbwBtAGEAbgAAAEsGkAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOAG8AdABvACAAUwBlAHIA"
            + "aQBmACAAQwBKAEsAIABTAEMAAAA5BpABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARgByAGUAZQBTAGEAbgBz"
            + "AAAAOwaQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4AbwB0AG8AIABTAGEAbgBzAAAAOSSQAQAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEYAcgBlAGUAUwBhAG4AcwAAAFMmkAEAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAABMAGkAYgBlAHIAYQB0AGkAbwBuACAAUwBhAG4AcwAAAEEAcgBpAGEAbAAAAEIABAABCI0YAABuBAAAaAEAAAAA"
            + "AAAAAAAAAAAAAAAAAQAAAAAAEQAAAF8AAAABAAMAAAAEAIOQAwAAABEAAABfAAAAAQADAAAAAwAAAAAAAAAnAwAgAAAAAAAEAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAEjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAIAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v8AAAEAAgAAAAAAAAAAAAAAAAAAAAAAAQAAAOCFn/L5T2gQq5EIACsn"
            + "s9kwAAAAfAAAAAYAAAABAAAAOAAAAAkAAABAAAAACgAAAEwAAAALAAAAWAAAAAwAAABkAAAADQAAAHAAAAACAAAA6f0AAB4AAAAC"
            + "AAAAMAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "7KUBAU0gCQQAAPASvwAAAAAAADAAAAAAAAgAAMQIAAAOAENhb2xhbjgwAAAAAAAAAAAAAAAAAAAAAAAACQQWAD0OAAAAAAAAAAAA"
            + "AGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8PAAUAAAABAAAA//8PAAYAAAABAAAA//8PAAAAAAAAAAAAAAAAAAAA"
            + "AACIAAAAAAD2AwAAAAAAAPYDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPYDAAAUAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoEAAAMAAAAFgQAAAwAAAAAAAAAAAAAAEMEAABwAgAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAswYAAGICAAAAAAAAAAAAAC4EAAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIE"
            + "AAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAGwAYQBpAG4AVABlAHgAdAAgAEIAbwBsAGQAVwBvAHIAZAAgAEkAdABhAGwAaQBjAFcA"
            + "bwByAGQAIABVAG4AZABlAHIAVwBvAHIAZAAgAG4AbwByAG0AYQBsAC4ADQBCAGkAZwBXAG8AcgBkACAAYQBuAGQAIABSAGUAZABX"
            + "AG8AcgBkACAAaABlAHIAZQAuAA0ASwBvAHIAZQBhAG4AIAB1rYysIABhAG4AZAAgADCuuMaExyAAdABlAHMAdAAuAA0AAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAIAAAUCAAAJAgAACYIAAA6CAAAPAgAAE4IAABeCAAAbggAAHgIAACGCAAAoggAAKYIAACwCAAAtggAAMIIAAAA"
            + "/QD7APkA9gDxAP0A+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACUIqBnBo/wAAAARDSjAAAAM+KgEDNggBAzUIAQAPAAgA"
            + "AGAIAACUCAAAxAgAAPkAAAAAAAAAAAAAAADtAAAAAAAAAAAAAAAA4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAobAAMkAGEkABOkAAAUpBsBQSQADBsAAyQAYSQAYIQAAF6EAABdhAAAQSQABhsAAyQAYSQAQSQAAAM7ADwwAEBQAABCUAIAH7CC"
            + "LiCwxkEhsG4EIrA3AiOQNwIkkDcCMlAAADGQWAIwcACAAAAzUAAAKDIADjAAAAAA/v8AAAEAAgAAAAAAAAAAAAAAAAAAAAAAAgAA"
            + "AALVzdWcLhsQk5cIACss+a5EAAAABdXN1ZwuGxCTlwgAKyz5rlwAAAAYAAAAAQAAAAEAAAAQAAAAAgAAAOn9AAAYAAAAAQAAAAEA"
            + "AAAQAAAAAgAAAOn9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAFIAbwBvAHQAIABFAG4AdAByAHkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUA////"
            + "//////8BAAAABgkCAAAAAADAAAAAAAAARgAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAIAZAAAAAAAAAQBDAG8AbQBwAE8AYgBqAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAgACAAAABAAAAP////8AAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAagAAAAAAAAABAE8AbABlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgACAP////8DAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAIAAAAUAAAAAAAAADEAVABhAGIAbABlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAOAAIA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAABUJAAAAAAAABQBTAHUAbQBt"
            + "AGEAcgB5AEkAbgBmAG8AcgBtAGEAdABpAG8AbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAgAFAAAABgAAAP////8AAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAArAAAAAAAAABXAG8AcgBkAEQAbwBjAHUAbQBlAG4AdAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgACAP///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAACsAAAA9DgAAAAAAAAUARABvAGMAdQBtAGUAbgB0AFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0AYQB0AGkAbwBu"
            + "AAAAAAAAAAAAAAA4AAIA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZAAAAHQAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////"
            + "//////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAAAAAAAAA=";

    private static final String PARA_DOC = ""
            + "0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAOwADAP7/CQAGAAAAAAAAAAAAAAABAAAAEgAAAAAAAAAAEAAAAgAAAAEAAAD+////AAAA"
            + "AAAAAAD/////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "///////////////////////////////////////////////////////////////////////////////////9//////////7///8E"
            + "AAAABQAAAAYAAAAHAAAACAAAAP7///8KAAAACwAAAAwAAAANAAAADgAAAA8AAAAQAAAAEQAAAP7///8TAAAA/v//////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "/////////////////////////////////////////////////////////////////1IAbwBvAHQAIABFAG4AdAByAHkAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//"
            + "/////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAQAAAP7////+////BAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAA"
            + "AAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAAB0A"
            + "AAAeAAAAHwAAACAAAAAhAAAAIgAAACMAAAAkAAAAJQAAACYAAAAnAAAA/v///ykAAAAqAAAA/v///ywAAAD+////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "////////////////////////////////////////////////////////////////////////////////////////////////////"
            + "//////////////////////////////8BAP7/AwoAAP////8GCQIAAAAAAMAAAAAAAABGGAAAAE1pY3Jvc29mdCBXb3JkLURva3Vt"
            + "ZW50AAoAAABNU1dvcmREb2MAEAAAAFdvcmQuRG9jdW1lbnQuOAD0ObJxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAEAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAB0ACgABAFsA"
            + "DwAAAAAAAAAAAFoAABDx/wIAWgAAAAYATgBvAHIAbQBhAGwAAAALAAAAMSQAKiQBQSQAAC8AQioAT0oDAFFKAwBDShgAbUgJBHNI"
            + "CQRQSgQAbkgECHRIBAheSgUAYUoYAF9IOQQAPAABEMEBsgE8AAAACQBIAGUAYQBkAGkAbgBnACAAMQAAAAIAAQAWAE9KBgBRSgYA"
            + "Q0owADUIAWFKLABcCAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQA/h/y//EANAAAABIARQBuAGQAbgBvAHQAZQAgAEMAaABh"
            + "AHIAYQBjAHQAZQByAHMAAAAAADYA/h/y/wEBNgAAABMARgBvAG8AdABuAG8AdABlACAAQwBoAGEAcgBhAGMAdABlAHIAcwAAAAAA"
            + "LgBVEPL/EQEuAAAACQBIAHkAcABlAHIAbABpAG4AawAAAAwAQioJcGgAAIAAPioBggD+HwEAsgGCAAAADwBIAG8AcgBpAHoAbwBu"
            + "AHQAYQBsACAATABpAG4AZQAAAE4AEgATpAAAFKQbASRkAAAAAE7GCAAAAAAAAAAAJWQAAAAAT8YIAAAAAAAAAAAmZAMDDwBQxgiA"
            + "gIAAAwMAACdkAAAAAFHGCAAAAAAAAAAABABDSgwANgAlEAEAMgE2AAAADwBFAG4AdgBlAGwAbwBwAGUAIABSAGUAdAB1AHIAbgAA"
            + "AAIAEwADADYIAQAwAP4fsQFCATAAAAAOAFQAYQBiAGwAZQAgAEMAbwBuAHQAZQBuAHQAcwAAAAIAFAAAAC4AIBABAFIBLgAAAAYA"
            + "RgBvAG8AdABlAHIAAAAQABUADcYIAALSEqUlAQIMJAEAAC4AHxABAGIBLgAAAAYASABlAGEAZABlAHIAAAAQABYADcYIAALSEqUl"
            + "AQIMJAEAAEQA/h8BAHIBRAAAABEASABlAGEAZABlAHIAIABhAG4AZAAgAEYAbwBvAHQAZQByAAAAEAAXAA3GCAAC0xKmJQECDCQB"
            + "AAAmAP4fAQCCASYAAAAFAEkAbgBkAGUAeAAAAAUAGAAMJAEABABeSgcAQAAiEAEAkgFAAAAABwBDAGEAcAB0AGkAbwBuAAAADQAZ"
            + "ABOkeAAUpHgADCQBABIAQ0oYADYIAV5KBwBhShgAXQgBIAAvELEBogEgAAAABABMAGkAcwB0AAAAAgAaAAQAXkoHAC4AQhABALIB"
            + "LgAAAAkAQgBvAGQAeQAgAFQAZQB4AHQAAAAKABsAE6QAABSkGwEAAD4A/h8BALIBPgAAAAcASABlAGEAZABpAG4AZwAAAA0AHAAT"
            + "pPAAFKQbAQYkAQAQAE9KCABRSggAQ0ocAGFKHAAAAAAAJwEAAAQAABAAAAAA/////wAIAABMCgAABgAAAAAIAABOCgAABwAAAAAA"
            + "AAAnAQAAAAAAAAIQAAAAAAAAACcBAABQAAAIAAAAAAkAAABHFpABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "VABpAG0AZQBzACAATgBlAHcAIABSAG8AbQBhAG4AAAA1FpABAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUwB5"
            + "AG0AYgBvAGwAAAAzJpABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQQByAGkAYQBsAAAAaRaQAQARAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEwAaQBiAGUAcgBhAHQAaQBvAG4AIABTAGUAcgBpAGYAAABUAGkAbQBlAHMAIABO"
            + "AGUAdwAgAFIAbwBtAGEAbgAAAEsGkAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOAG8AdABvACAAUwBlAHIA"
            + "aQBmACAAQwBKAEsAIABTAEMAAAA5BpABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARgByAGUAZQBTAGEAbgBz"
            + "AAAAOwaQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4AbwB0AG8AIABTAGEAbgBzAAAAOSSQAQAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEYAcgBlAGUAUwBhAG4AcwAAAFMmkAEAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAABMAGkAYgBlAHIAYQB0AGkAbwBuACAAUwBhAG4AcwAAAEEAcgBpAGEAbAAAAEIABAABCI0YAABuBAAAaAEAAAAA"
            + "AAAAAAAAAAAAAAAAAQAAAAAAMAAAACEBAAABAAYAAAAEAIOQBgAAADAAAAAhAQAAAQAGAAAABgAAAAAAAAAnAwAgAAAAAAAEAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAEjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAIAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v8AAAEAAgAAAAAAAAAAAAAAAAAAAAAAAQAAAOCFn/L5T2gQq5EIACsn"
            + "s9kwAAAAfAAAAAYAAAABAAAAOAAAAAkAAABAAAAACgAAAEwAAAALAAAAWAAAAAwAAABkAAAADQAAAHAAAAACAAAA6f0AAB4AAAAC"
            + "AAAAMAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "/v8AAAEAAgAAAAAAAAAAAAAAAAAAAAAAAgAAAALVzdWcLhsQk5cIACss+a5EAAAABdXN1ZwuGxCTlwgAKyz5rlwAAAAYAAAAAQAA"
            + "AAEAAAAQAAAAAgAAAOn9AAAYAAAAAQAAAAEAAAAQAAAAAgAAAOn9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAADspQEBTSAJBAAA8BK/AAAAAAAAMAAAAAAACAAATgoAAA4AQ2FvbGFuODAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAJBBYAPRAAAAAAAAAAAAAAJwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//w8ABgAAAAEAAAD//w8ABwAAAAEA"
            + "AAD//w8AAAAAAAAAAAAAAAAAAAAAAIgAAAAAAPYDAAAAAAAA9gMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9gMA"
            + "ABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgQAAAwAAAAWBAAADAAAAAAAAAAAAAAAQwQAAHAC"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgQAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACzBgAAYgIAAAAAAAAAAAAALgQAABUAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAIgQAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgDZAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEwAZQBmAHQAUABhAHIAYQAgAGEAbABpAGcAbgBlAGQA"
            + "IAB0AG8AIAB0AGgAZQAgAGwAZQBmAHQAIABtAGEAcgBnAGkAbgAuAA0AQwBlAG4AdABlAHIAUABhAHIAYQAgAGkAbgAgAHQAaABl"
            + "ACAAbQBpAGQAZABsAGUALgANAFIAaQBnAGgAdABQAGEAcgBhACAAdABvACAAdABoAGUAIAByAGkAZwBoAHQALgANAEoAdQBzAHQA"
            + "aQBmAHkAUABhAHIAYQAgAHMAdAByAGUAdABjAGgAZQBkACAAYQBjAHIAbwBzAHMAIAB0AGgAZQAgAGYAdQBsAGwAIAB3AGkAZAB0"
            + "AGgAIABvAGYAIAB0AGgAZQAgAHQAZQB4AHQAIABjAG8AbAB1AG0AbgAgAHMAbwAgAGIAbwB0AGgAIABlAGQAZwBlAHMAIABsAGkA"
            + "bgBlACAAdQBwACAAZQB2AGUAbgBsAHkAIABvAG4AIABtAHUAbAB0AGkAcABsAGUAIABsAGkAbgBlAHMAIABvAGYAIAByAHUAbgBu"
            + "AGkAbgBnACAAdABlAHgAdAAgAGgAZQByAGUALgANAEkAbgBkAGUAbgB0AFAAYQByAGEAIAB3AGkAdABoACAAYQAgAGwAZQBmAHQA"
            + "IABpAG4AZABlAG4AdAAuAA0ARgBpAHIAcwB0AEwAaQBuAGUAUABhAHIAYQAgAHcAaQB0AGgAIABhACAAZgBpAHIAcwB0AC0AbABp"
            + "AG4AZQAgAGkAbgBkAGUAbgB0ACAAbwBuAGwAeQAuAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAACAAATAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAQAIAABKCAAAfggAAK4IAAC2CQAA9AkAAE4KAADzAAAAAAAAAAAAAAAA5wAAAAAAAAAAAAAAANsAAAAAAAAAAAAAAADPAAAA"
            + "AAAAAAAAAAAAwwAAAAAAAAAAAAAAALMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQGwADJABhJABghDcC"
            + "XoQAAF2EAAATpAAAFKQbAUEkAAwbAAMkAGEkAGCEAABehDcCXYQAAEEkAAwbAAMkA2EkA2CEAABehAAAXYQAAEEkAAwbAAMkAmEk"
            + "AmCEAABehAAAXYQAAEEkAAwbAAMkAWEkAWCEAABehAAAXYQAAEEkAAwbAAMkAGEkAGCEAABehAAAXYQAAEEkAAAGOwA8MABAUAAA"
            + "QlACAB+wgi4gsMZBIbBuBCKwNwIjkDcCJJA3AjJQAAAxkFgCMHAAgAAAM1AAACgyAA4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSAG8AbwB0ACAARQBuAHQAcgB5AAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgAFAP//////////AQAAAAYJAgAAAAAAwAAAAAAAAEYA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAMAAABACwAAAAAAAAEAQwBvAG0AcABPAGIAagAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAASAAIAAgAAAAQAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AGoAAAAAAAAAAQBPAGwAZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoA"
            + "AgD/////AwAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAFAAAAAAAAAAxAFQAYQBiAGwAZQAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgACAP///////////////wAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAVCQAAAAAAAAUAUwB1AG0AbQBhAHIAeQBJAG4AZgBvAHIAbQBhAHQAaQBv"
            + "AG4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAIABQAAAAYAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAKAAAAKwAAAAAAAAAVwBvAHIAZABEAG8AYwB1AG0AZQBuAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAABoAAgD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAPRAAAAAAAAAFAEQA"
            + "bwBjAHUAbQBlAG4AdABTAHUAbQBtAGEAcgB5AEkAbgBmAG8AcgBtAGEAdABpAG8AbgAAAAAAAAAAAAAAOAACAP//////////////"
            + "/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsAAAB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAA";

    private static byte[] decode(String b64) {
        return Base64.getDecoder().decode(b64);
    }

    private static Map<String, TextStyle> runStylesByText(RenderedDocument doc) {
        Map<String, TextStyle> map = new HashMap<>();
        for (RenderedPage page : doc.pages) {
            for (RenderedBlock block : page.blocks) {
                RenderedParagraph paragraph = block.paragraph;
                if (paragraph == null) continue;
                for (RenderedRun run : paragraph.runs) {
                    if (run.text != null && !run.text.isEmpty()) map.put(run.text, run.style);
                }
            }
        }
        return map;
    }

    private static ParagraphStyle paragraphStyleByPrefix(RenderedDocument doc, String prefix) {
        for (RenderedPage page : doc.pages) {
            for (RenderedBlock block : page.blocks) {
                RenderedParagraph paragraph = block.paragraph;
                if (paragraph == null) continue;
                String t = paragraph.plainText();
                if (t != null && t.startsWith(prefix)) return paragraph.style;
            }
        }
        return null;
    }

    @Test
    public void compoundReaderExposesWordStreams() throws Exception {
        CompoundFileReader cfb = new CompoundFileReader(decode(PLAIN_DOC));
        byte[] wd = cfb.getStream("WordDocument");
        assertNotNull("WordDocument stream should be present", wd);
        // The FIB starts with wIdent 0xA5EC, stored little-endian as EC A5.
        assertTrue("WordDocument should start with the FIB signature",
                (wd[0] & 0xFF) == 0xEC && (wd[1] & 0xFF) == 0xA5);
        assertNotNull("table stream should be present", cfb.getStream("1Table"));
    }

    @Test
    public void extractsParagraphsFromRealDoc() throws Exception {
        RenderedDocument doc = DocLegacyLayoutExtractor.extractFromBytes(decode(PLAIN_DOC), "sample", 28);
        assertNotNull("rendered document should not be null", doc);
        assertTrue("document should have at least one page", !doc.pages.isEmpty());

        StringBuilder all = new StringBuilder();
        for (RenderedPage page : doc.pages) {
            for (RenderedBlock block : page.blocks) {
                if (block.paragraph != null) all.append(block.paragraph.plainText()).append('\n');
            }
        }
        String text = all.toString();
        assertTrue("title paragraph", text.contains("Readwide legacy .doc test document"));
        assertTrue("english paragraph", text.contains("exercise the piece table"));
        assertTrue("korean paragraph", text.contains("\uB450 \uBC88\uC9F8 \uBB38\uB2E8\uC740 \uD55C\uAE00\uC785\uB2C8\uB2E4"));
        assertTrue("mixed paragraph", text.contains("mixed \uD55C\uAE00 and English 12345"));
    }

    @Test
    public void extractsCharacterFormatting() throws Exception {
        RenderedDocument doc = DocLegacyLayoutExtractor.extractFromBytes(decode(FORMATTED_DOC), "formatted", 28);
        assertNotNull("rendered document should not be null", doc);
        Map<String, TextStyle> styles = runStylesByText(doc);

        assertNotNull("bold run should exist as its own styled run", styles.get("BoldWord"));
        assertEquals("BoldWord should be bold", Boolean.TRUE, styles.get("BoldWord").bold);
        assertEquals("ItalicWord should be italic", Boolean.TRUE, styles.get("ItalicWord").italic);
        assertEquals("UnderWord should be underlined", Boolean.TRUE, styles.get("UnderWord").underline);

        TextStyle big = styles.get("BigWord");
        assertNotNull("size run should exist", big);
        assertNotNull("size run should carry a font size", big.fontSizePt);
        assertEquals("BigWord should be 24pt", 24.0f, big.fontSizePt, 0.01f);

        TextStyle red = styles.get("RedWord");
        assertNotNull("color run should exist", red);
        assertEquals("RedWord should be red", "#FF0000", red.color);

        assertEquals("Korean bold run", Boolean.TRUE, styles.get("\uAD75\uAC8C").bold);
        assertEquals("Korean italic run", Boolean.TRUE, styles.get("\uAE30\uC6B8\uC784").italic);
    }

    @Test
    public void extractsParagraphProperties() throws Exception {
        RenderedDocument doc = DocLegacyLayoutExtractor.extractFromBytes(decode(PARA_DOC), "para", 28);
        assertNotNull("rendered document should not be null", doc);

        assertEquals("LeftPara stays left", ParagraphStyle.Alignment.LEFT,
                paragraphStyleByPrefix(doc, "LeftPara").alignment);
        assertEquals("CenterPara is centered", ParagraphStyle.Alignment.CENTER,
                paragraphStyleByPrefix(doc, "CenterPara").alignment);
        assertEquals("RightPara is right aligned", ParagraphStyle.Alignment.RIGHT,
                paragraphStyleByPrefix(doc, "RightPara").alignment);
        assertEquals("JustifyPara is justified", ParagraphStyle.Alignment.JUSTIFY,
                paragraphStyleByPrefix(doc, "JustifyPara").alignment);

        ParagraphStyle indent = paragraphStyleByPrefix(doc, "IndentPara");
        assertNotNull("IndentPara should have a left indent", indent.marginLeftPt);
        assertEquals("IndentPara left indent about 28pt (1cm)", 28.35f, indent.marginLeftPt, 1.5f);

        ParagraphStyle firstLine = paragraphStyleByPrefix(doc, "FirstLinePara");
        assertNotNull("FirstLinePara should have a first-line indent", firstLine.textIndentPt);
        assertEquals("FirstLinePara first-line indent about 28pt (1cm)", 28.35f, firstLine.textIndentPt, 1.5f);
    }
}
